// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using planinarenje.Data;

#nullable disable

namespace planinarenje.Migrations
{
    [DbContext(typeof(PlaninarstvoDbContext))]
    [Migration("20260508071058_DodanaObavijest")]
    partial class DodanaObavijest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("planinarenje.Entiteti.Fotografija", b =>
                {
                    b.Property<int>("IdFotografija")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdFotografija"));

                    b.Property<DateTime>("DatumUploada")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdPosjet")
                        .HasColumnType("int");

                    b.Property<string>("NazivDatoteke")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Opis")
                        .HasColumnType("longtext");

                    b.Property<string>("PutanjaDatoteke")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TipSlike")
                        .HasColumnType("int");

                    b.HasKey("IdFotografija");

                    b.HasIndex("IdPosjet");

                    b.ToTable("Fotografije");

                    b.HasData(
                        new
                        {
                            IdFotografija = 1,
                            DatumUploada = new DateTime(2026, 4, 5, 12, 5, 0, 0, DateTimeKind.Unspecified),
                            IdPosjet = 1,
                            NazivDatoteke = "vis_luka_selfie.jpg",
                            Opis = "Selfie korisnika Luke na vrhu Vis.",
                            PutanjaDatoteke = "/slike/posjeti/vis_luka_selfie.jpg",
                            TipSlike = 0
                        },
                        new
                        {
                            IdFotografija = 2,
                            DatumUploada = new DateTime(2026, 4, 12, 10, 5, 0, 0, DateTimeKind.Unspecified),
                            IdPosjet = 2,
                            NazivDatoteke = "okic_luka_selfie.jpg",
                            Opis = "Fotografija Luke kod oznake vrha Okić.",
                            PutanjaDatoteke = "/slike/posjeti/okic_luka_selfie.jpg",
                            TipSlike = 0
                        },
                        new
                        {
                            IdFotografija = 3,
                            DatumUploada = new DateTime(2026, 4, 19, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            IdPosjet = 3,
                            NazivDatoteke = "japetic_luka_selfie.jpg",
                            Opis = "Selfie na vrhu Japetić uz piramidu.",
                            PutanjaDatoteke = "/slike/posjeti/japetic_luka_selfie.jpg",
                            TipSlike = 0
                        },
                        new
                        {
                            IdFotografija = 4,
                            DatumUploada = new DateTime(2026, 4, 8, 12, 50, 0, 0, DateTimeKind.Unspecified),
                            IdPosjet = 4,
                            NazivDatoteke = "vis_test_selfie.jpg",
                            Opis = "Testni korisnik na vrhu Vis.",
                            PutanjaDatoteke = "/slike/posjeti/vis_test_selfie.jpg",
                            TipSlike = 0
                        },
                        new
                        {
                            IdFotografija = 5,
                            DatumUploada = new DateTime(2026, 4, 26, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            IdPosjet = 5,
                            NazivDatoteke = "sljeme_test_selfie.jpg",
                            Opis = "Testni korisnik na vrhu Sljeme kod oznake.",
                            PutanjaDatoteke = "/slike/posjeti/sljeme_test_selfie.jpg",
                            TipSlike = 0
                        });
                });

            modelBuilder.Entity("planinarenje.Entiteti.Knjizica", b =>
                {
                    b.Property<int>("IdKnjizica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdKnjizica"));

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdKorisnik")
                        .HasColumnType("int");

                    b.Property<string>("Napomena")
                        .HasColumnType("longtext");

                    b.Property<bool>("StatusAktivna")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IdKnjizica");

                    b.HasIndex("IdKorisnik")
                        .IsUnique();

                    b.ToTable("Knjizice");

                    b.HasData(
                        new
                        {
                            IdKnjizica = 1,
                            DatumKreiranja = new DateTime(2026, 4, 1, 9, 5, 0, 0, DateTimeKind.Unspecified),
                            IdKorisnik = 1,
                            Napomena = "Glavna digitalna knjižica korisnika Luka Bošnjak.",
                            StatusAktivna = true
                        },
                        new
                        {
                            IdKnjizica = 2,
                            DatumKreiranja = new DateTime(2026, 4, 1, 9, 20, 0, 0, DateTimeKind.Unspecified),
                            IdKorisnik = 2,
                            Napomena = "Testna digitalna knjižica za provjeru funkcionalnosti aplikacije.",
                            StatusAktivna = true
                        });
                });

            modelBuilder.Entity("planinarenje.Entiteti.KontrolnaTocka", b =>
                {
                    b.Property<int>("IdKontrolnaTocka")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdKontrolnaTocka"));

                    b.Property<string>("GUIDOznaka")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("IdPodrucje")
                        .HasColumnType("int");

                    b.Property<string>("Koordinate")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("NadmorskaVisina")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Opis")
                        .HasColumnType("longtext");

                    b.Property<string>("OpisZiga")
                        .HasColumnType("longtext");

                    b.Property<int>("TipKontrolneTocke")
                        .HasColumnType("int");

                    b.HasKey("IdKontrolnaTocka");

                    b.HasIndex("GUIDOznaka")
                        .IsUnique();

                    b.HasIndex("IdPodrucje");

                    b.ToTable("KontrolneTocke");

                    b.HasData(
                        new
                        {
                            IdKontrolnaTocka = 1,
                            GUIDOznaka = "KT-HPO-2-1-VIS",
                            IdPodrucje = 2,
                            Koordinate = "N/A",
                            NadmorskaVisina = 437,
                            Naziv = "Moslavačka gora – vrh Vis",
                            Opis = "Najviši vrh Moslavačke gore i dobra početna kontrolna točka za početničke obilaznike.",
                            OpisZiga = "Metalni žig na vršnoj oznaci.",
                            TipKontrolneTocke = 0
                        },
                        new
                        {
                            IdKontrolnaTocka = 2,
                            GUIDOznaka = "KT-HPO-4-4-SLJEME",
                            IdPodrucje = 4,
                            Koordinate = "N 45° 53' 57.4'' E 15° 56' 50.6''",
                            NadmorskaVisina = 1033,
                            Naziv = "Sljeme – vrh",
                            Opis = "Najviši vrh Medvednice; vrh je lako dostupan i planinarima i izletnicima.",
                            OpisZiga = "Metalni žig vrha nalazi se na promidžbenom panou kod televizijskog tornja.",
                            TipKontrolneTocke = 0
                        },
                        new
                        {
                            IdKontrolnaTocka = 3,
                            GUIDOznaka = "KT-HPO-5-1-OKIC",
                            IdPodrucje = 5,
                            Koordinate = "N 45° 44' 55.4'' E 15° 42' 24.0''",
                            NadmorskaVisina = 499,
                            Naziv = "Okić – vrh",
                            Opis = "Stari grad i vršna gradina s vidikom prema Zagrebu i Medvednici.",
                            OpisZiga = "Metalni žig vrha ugrađen je na zid u najvišem dijelu gradine.",
                            TipKontrolneTocke = 0
                        },
                        new
                        {
                            IdKontrolnaTocka = 4,
                            GUIDOznaka = "KT-HPO-5-4-JAPETIC",
                            IdPodrucje = 5,
                            Koordinate = "N 45° 44' 56.3'' E 15° 36' 32.8''",
                            NadmorskaVisina = 879,
                            Naziv = "Japetić – vrh",
                            Opis = "Najviši vrh Samoborskoga gorja; poznat po piramidi i domu Žitnica.",
                            OpisZiga = "Metalni žig ugrađen je na konstrukciju piramide.",
                            TipKontrolneTocke = 0
                        },
                        new
                        {
                            IdKontrolnaTocka = 5,
                            GUIDOznaka = "KT-HPO-11-2-ZAVIZAN",
                            IdPodrucje = 11,
                            Koordinate = "N/A",
                            NadmorskaVisina = 1676,
                            Naziv = "Veliki Zavižan – vrh",
                            Opis = "Jedan od najpoznatijih vrhova Sjevernog Velebita s vrlo atraktivnim pogledima.",
                            OpisZiga = "Žig kontrolne točke nalazi se na vrhu ili u blizini planinarskog doma Zavižan.",
                            TipKontrolneTocke = 0
                        });
                });

            modelBuilder.Entity("planinarenje.Entiteti.Korisnik", b =>
                {
                    b.Property<int>("IdKorisnik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdKorisnik"));

                    b.Property<string>("BrojMobitela")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("DatumRegistracije")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DatumRodenja")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ProfilnaSlika")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("StatusAktivan")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IdKorisnik");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("KorisnickoIme")
                        .IsUnique();

                    b.ToTable("Korisnici");

                    b.HasData(
                        new
                        {
                            IdKorisnik = 1,
                            BrojMobitela = "0979545897",
                            DatumRegistracije = new DateTime(2026, 4, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumRodenja = new DateTime(2004, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "luka.bosnjak92@gmail.com",
                            Ime = "Luka",
                            KorisnickoIme = "Boss",
                            PasswordHash = "123456789",
                            Prezime = "Bošnjak",
                            ProfilnaSlika = "/Slike/Profil/Boss.jpeg",
                            StatusAktivan = true
                        },
                        new
                        {
                            IdKorisnik = 2,
                            DatumRegistracije = new DateTime(2026, 4, 1, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            DatumRodenja = new DateTime(2005, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test123@gmail.com",
                            Ime = "Test",
                            KorisnickoIme = "Test",
                            PasswordHash = "123456789",
                            Prezime = "Test",
                            ProfilnaSlika = "/Slike/Profil/test.jpg",
                            StatusAktivan = true
                        });
                });

            modelBuilder.Entity("planinarenje.Entiteti.KorisnikMedalja", b =>
                {
                    b.Property<int>("IdKorisnikMedalja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdKorisnikMedalja"));

                    b.Property<DateTime>("DatumDodjele")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdKorisnik")
                        .HasColumnType("int");

                    b.Property<int>("IdMedalja")
                        .HasColumnType("int");

                    b.Property<string>("Napomena")
                        .HasColumnType("longtext");

                    b.HasKey("IdKorisnikMedalja");

                    b.HasIndex("IdKorisnik");

                    b.HasIndex("IdMedalja");

                    b.ToTable("KorisnikMedalje");

                    b.HasData(
                        new
                        {
                            IdKorisnikMedalja = 1,
                            DatumDodjele = new DateTime(2026, 4, 19, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IdKorisnik = 1,
                            IdMedalja = 1,
                            Napomena = "Korisnik je zadovoljio uvjet početničke medalje jer ima evidentiran obilazak područja 2 (Moslavačka gora i Bilogora), gdje je prag 1 KT."
                        },
                        new
                        {
                            IdKorisnikMedalja = 2,
                            DatumDodjele = new DateTime(2026, 4, 8, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            IdKorisnik = 2,
                            IdMedalja = 1,
                            Napomena = "Korisnik je zadovoljio uvjet početničke medalje jer ima evidentiran obilazak područja 2 (Moslavačka gora i Bilogora), gdje je prag 1 KT."
                        });
                });

            modelBuilder.Entity("planinarenje.Entiteti.Medalja", b =>
                {
                    b.Property<int>("IdMedalja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMedalja"));

                    b.Property<int>("MinimalanBrojKontrolnihTocaka")
                        .HasColumnType("int");

                    b.Property<int>("MinimalanBrojPodrucja")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Opis")
                        .HasColumnType("longtext");

                    b.HasKey("IdMedalja");

                    b.ToTable("Medalje");

                    b.HasData(
                        new
                        {
                            IdMedalja = 1,
                            MinimalanBrojKontrolnihTocaka = 1,
                            MinimalanBrojPodrucja = 1,
                            Naziv = "Početnik",
                            Opis = "Osnovna medalja za prvi ispravno evidentirani obilazak područja."
                        },
                        new
                        {
                            IdMedalja = 2,
                            MinimalanBrojKontrolnihTocaka = 25,
                            MinimalanBrojPodrucja = 10,
                            Naziv = "Brončana značka",
                            Opis = "Potrebno je obići zadani broj KT-a iz 10 područja i ukupno 25 KT-a."
                        },
                        new
                        {
                            IdMedalja = 3,
                            MinimalanBrojKontrolnihTocaka = 50,
                            MinimalanBrojPodrucja = 15,
                            Naziv = "Srebrna značka",
                            Opis = "Potrebno je obići zadani broj KT-a iz 15 područja i ukupno 50 KT-a, uz obaveznu Dinaru (Sinjal)."
                        },
                        new
                        {
                            IdMedalja = 4,
                            MinimalanBrojKontrolnihTocaka = 75,
                            MinimalanBrojPodrucja = 20,
                            Naziv = "Zlatna značka",
                            Opis = "Potrebno je obići zadani broj KT-a iz svih 20 područja i ukupno 75 KT-a."
                        },
                        new
                        {
                            IdMedalja = 5,
                            MinimalanBrojKontrolnihTocaka = 100,
                            MinimalanBrojPodrucja = 20,
                            Naziv = "Posebno priznanje",
                            Opis = "Potrebno je obići 100 KT-a uz ispunjene uvjete za zlatnu značku."
                        },
                        new
                        {
                            IdMedalja = 6,
                            MinimalanBrojKontrolnihTocaka = 125,
                            MinimalanBrojPodrucja = 20,
                            Naziv = "Visoko priznanje",
                            Opis = "Potrebno je obići 125 KT-a uz ispunjene uvjete za posebno priznanje."
                        },
                        new
                        {
                            IdMedalja = 7,
                            MinimalanBrojKontrolnihTocaka = 155,
                            MinimalanBrojPodrucja = 20,
                            Naziv = "Najviše priznanje",
                            Opis = "Potrebno je obići 155 KT-a uz ispunjene uvjete za visoko priznanje."
                        });
                });

            modelBuilder.Entity("planinarenje.Entiteti.Obavijest", b =>
                {
                    b.Property<int>("IdObavijest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdObavijest"));

                    b.Property<DateTime>("DatumObjave")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdKorisnik")
                        .HasColumnType("int");

                    b.Property<bool>("JeAktivna")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Sadrzaj")
                        .HasColumnType("longtext");

                    b.HasKey("IdObavijest");

                    b.HasIndex("IdKorisnik");

                    b.ToTable("Obavijesti");

                    b.HasData(
                        new
                        {
                            IdObavijest = 1,
                            DatumObjave = new DateTime(2026, 4, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IdKorisnik = 1,
                            JeAktivna = true,
                            Naslov = "Dobrodošli u planinarsku aplikaciju",
                            Sadrzaj = "Aplikacija je pokrenuta i spremna za korištenje."
                        },
                        new
                        {
                            IdObavijest = 2,
                            DatumObjave = new DateTime(2026, 4, 15, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            IdKorisnik = 1,
                            JeAktivna = true,
                            Naslov = "Nova ruta dodana: Zavižan",
                            Sadrzaj = "Dodana je kružna tura od doma Zavižan preko Balinovca."
                        },
                        new
                        {
                            IdObavijest = 3,
                            DatumObjave = new DateTime(2026, 4, 28, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            IdKorisnik = 2,
                            JeAktivna = false,
                            Naslov = "Održavanje sustava",
                            Sadrzaj = "Planirano održavanje 30. travnja od 22:00 do 23:00."
                        });
                });

            modelBuilder.Entity("planinarenje.Entiteti.PlaninarskaUdruga", b =>
                {
                    b.Property<int>("IdPlaninarskaUdruga")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPlaninarskaUdruga"));

                    b.Property<string>("Adresa")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("BrojClanova")
                        .HasColumnType("int");

                    b.Property<string>("BrojTelefona")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Grad")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("OIB")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("PostanskiBroj")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Zupanija")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdPlaninarskaUdruga");

                    b.HasIndex("OIB")
                        .IsUnique();

                    b.ToTable("PlaninarskeUdruge");

                    b.HasData(
                        new
                        {
                            IdPlaninarskaUdruga = 1,
                            Adresa = "p.p. 233",
                            BrojClanova = 350,
                            Email = "hpd.mosor@hps.hr",
                            Grad = "Split",
                            Naziv = "HPD Mosor",
                            OIB = "40461293872",
                            PostanskiBroj = "21000",
                            Zupanija = "Splitsko-dalmatinska"
                        },
                        new
                        {
                            IdPlaninarskaUdruga = 2,
                            Adresa = "Dubravica 27a",
                            BrojClanova = 180,
                            Email = "hpd.gora@hps.hr",
                            Grad = "Zagreb",
                            Naziv = "HPD Gora",
                            OIB = "48938096579",
                            PostanskiBroj = "10000",
                            Zupanija = "Grad Zagreb"
                        },
                        new
                        {
                            IdPlaninarskaUdruga = 3,
                            Adresa = "Mala vrata 20",
                            BrojClanova = 120,
                            Email = "pd.zavizan@hps.hr",
                            Grad = "Senj",
                            Naziv = "PD Zavižan",
                            OIB = "95873199484",
                            PostanskiBroj = "53270",
                            Zupanija = "Ličko-senjska"
                        },
                        new
                        {
                            IdPlaninarskaUdruga = 4,
                            Adresa = "Majke Margarite 6",
                            BrojClanova = 220,
                            Email = "pd.paklenica@hps.hr",
                            Grad = "Zadar",
                            Naziv = "PD Paklenica",
                            OIB = "92966614510",
                            PostanskiBroj = "23000",
                            Zupanija = "Zadarska"
                        },
                        new
                        {
                            IdPlaninarskaUdruga = 5,
                            Adresa = "Andrije Hebranga 26",
                            BrojClanova = 95,
                            BrojTelefona = "0991234567",
                            Email = "info@pddr-maks-plotnikov.hr",
                            Grad = "Samobor",
                            Naziv = "PD Dr. Maks Plotnikov",
                            OIB = "12345678901",
                            PostanskiBroj = "10430",
                            Zupanija = "Zagrebačka"
                        });
                });

            modelBuilder.Entity("planinarenje.Entiteti.PlaninarskiObjekt", b =>
                {
                    b.Property<int>("IdPlaninarskiObjekt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPlaninarskiObjekt"));

                    b.Property<string>("Adresa")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("IdPlaninarskaUdruga")
                        .HasColumnType("int");

                    b.Property<int>("IdPodrucje")
                        .HasColumnType("int");

                    b.Property<bool>("ImaHranu")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ImaNocenje")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ImeOdgovorneOsobe")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("Kapacitet")
                        .HasColumnType("int");

                    b.Property<int?>("NadmorskaVisina")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Opis")
                        .HasColumnType("longtext");

                    b.Property<string>("RadnoVrijemeOpis")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefon")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("TipObjekta")
                        .HasColumnType("int");

                    b.HasKey("IdPlaninarskiObjekt");

                    b.HasIndex("IdPlaninarskaUdruga");

                    b.HasIndex("IdPodrucje");

                    b.ToTable("PlaninarskiObjekti");

                    b.HasData(
                        new
                        {
                            IdPlaninarskiObjekt = 1,
                            Adresa = "Okić, Samobor",
                            Email = "aplantosar@gmail.com",
                            IdPlaninarskaUdruga = 5,
                            IdPodrucje = 5,
                            ImaHranu = true,
                            ImaNocenje = true,
                            ImeOdgovorneOsobe = "Stjepan Jandrečić",
                            Kapacitet = 14,
                            NadmorskaVisina = 411,
                            Naziv = "Planinarski dom Dr. Maks Plotnikov",
                            Opis = "Dom podno ruševina Okić-grada; polazišna je točka za Okić i okolne putove.",
                            RadnoVrijemeOpis = "Otvoren vikendom i blagdanima.",
                            Telefon = "0918909624",
                            TipObjekta = 0
                        },
                        new
                        {
                            IdPlaninarskiObjekt = 2,
                            Adresa = "Samoborsko gorje",
                            IdPlaninarskaUdruga = 2,
                            IdPodrucje = 5,
                            ImaHranu = true,
                            ImaNocenje = true,
                            ImeOdgovorneOsobe = "Dežurni domar",
                            Kapacitet = 25,
                            NadmorskaVisina = 691,
                            Naziv = "Planinarski dom Željezničar",
                            Opis = "Popularan planinarski dom u Samoborskom i Žumberačkom gorju.",
                            RadnoVrijemeOpis = "Prema rasporedu dežurstva i vikendom.",
                            TipObjekta = 0
                        },
                        new
                        {
                            IdPlaninarskiObjekt = 3,
                            Adresa = "Velebit, Senj",
                            Email = "pd.zavizan@hps.hr",
                            IdPlaninarskaUdruga = 3,
                            IdPodrucje = 11,
                            ImaHranu = false,
                            ImaNocenje = true,
                            ImeOdgovorneOsobe = "Dežurni član društva",
                            Kapacitet = 12,
                            NadmorskaVisina = 328,
                            Naziv = "Planinarska kuća Sijaset",
                            Opis = "Niži planinarski objekt na Velebitu, pogodan kao polazište za ture.",
                            RadnoVrijemeOpis = "Povremeno otvorena ili po dogovoru.",
                            TipObjekta = 1
                        },
                        new
                        {
                            IdPlaninarskiObjekt = 4,
                            Adresa = "Velika Paklenica",
                            Email = "pd.paklenica@hps.hr",
                            IdPlaninarskaUdruga = 4,
                            IdPodrucje = 13,
                            ImaHranu = true,
                            ImaNocenje = true,
                            ImeOdgovorneOsobe = "Irena Šaran",
                            Kapacitet = 44,
                            NadmorskaVisina = 480,
                            Naziv = "Planinarski dom Paklenica",
                            Opis = "Dom na početku klanca Velike Paklenice s hranom, pićem i noćenjem.",
                            RadnoVrijemeOpis = "Otvoren stalno.",
                            Telefon = "0977557654",
                            TipObjekta = 0
                        },
                        new
                        {
                            IdPlaninarskiObjekt = 5,
                            Adresa = "Mosor, Split",
                            Email = "hpd.mosor@hps.hr",
                            IdPlaninarskaUdruga = 1,
                            IdPodrucje = 18,
                            ImaHranu = false,
                            ImaNocenje = true,
                            ImeOdgovorneOsobe = "Dežurna osoba društva",
                            Kapacitet = 20,
                            NadmorskaVisina = 872,
                            Naziv = "Planinarska kuća Lugarnica",
                            Opis = "Planinarska kuća na Mosoru pogodna za kraće i srednje duge uspone.",
                            RadnoVrijemeOpis = "Otvorenost prema obavijesti društva.",
                            TipObjekta = 1
                        });
                });

            modelBuilder.Entity("planinarenje.Entiteti.Podrucje", b =>
                {
                    b.Property<int>("IdPodrucje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPodrucje"));

                    b.Property<int>("MinimalanBrojKTZaObilazak")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Opis")
                        .HasColumnType("longtext");

                    b.Property<string>("Regija")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("IdPodrucje");

                    b.ToTable("Podrucja");

                    b.HasData(
                        new
                        {
                            IdPodrucje = 1,
                            MinimalanBrojKTZaObilazak = 2,
                            Naziv = "Slavonija",
                            Opis = "Nizinsko i brežuljkasto područje istočne Hrvatske s Papukom, Psunjem, Krndijom i drugim slavonskim gorjima.",
                            Regija = "Istočna Hrvatska"
                        },
                        new
                        {
                            IdPodrucje = 2,
                            MinimalanBrojKTZaObilazak = 1,
                            Naziv = "Moslavačka gora i Bilogora",
                            Opis = "Niža šumovita gorja s kraćim planinarskim usponima i manjim brojem kontrolnih točaka.",
                            Regija = "Središnja Hrvatska"
                        },
                        new
                        {
                            IdPodrucje = 3,
                            MinimalanBrojKTZaObilazak = 3,
                            Naziv = "Hrvatsko zagorje i Međimurje",
                            Opis = "Brežuljkasto područje s vidikovcima, utvrdama i poznatim vrhovima kao što su Ivanščica i Ravna gora.",
                            Regija = "Sjeverna Hrvatska"
                        },
                        new
                        {
                            IdPodrucje = 4,
                            MinimalanBrojKTZaObilazak = 2,
                            Naziv = "Medvednica",
                            Opis = "Planina iznad Zagreba s gusto razvijenom mrežom putova, domova i kontrolnih točaka.",
                            Regija = "Središnja Hrvatska"
                        },
                        new
                        {
                            IdPodrucje = 5,
                            MinimalanBrojKTZaObilazak = 2,
                            Naziv = "Samoborsko gorje",
                            Opis = "Popularno planinarsko područje zapadno od Zagreba, poznato po Okiću, Japetiću i Oštrcu.",
                            Regija = "Središnja Hrvatska"
                        },
                        new
                        {
                            IdPodrucje = 6,
                            MinimalanBrojKTZaObilazak = 1,
                            Naziv = "Žumberačka gora",
                            Opis = "Planinsko i granično područje s višim vrhovima i rjeđe naseljenim grebenima.",
                            Regija = "Središnja Hrvatska"
                        },
                        new
                        {
                            IdPodrucje = 7,
                            MinimalanBrojKTZaObilazak = 1,
                            Naziv = "Karlovačko pokuplje, Kordun i Banovina",
                            Opis = "Područje nižih gora i šumovitih uzvisina južno od Karlovca i prema Banovini.",
                            Regija = "Središnja Hrvatska"
                        },
                        new
                        {
                            IdPodrucje = 8,
                            MinimalanBrojKTZaObilazak = 4,
                            Naziv = "Gorski kotar - južni dio",
                            Opis = "Dio Gorskog kotara s višim vrhovima, stjenovitim skupinama i zahtjevnijim usponima.",
                            Regija = "Gorska Hrvatska"
                        },
                        new
                        {
                            IdPodrucje = 9,
                            MinimalanBrojKTZaObilazak = 3,
                            Naziv = "Gorski kotar - sjeverni dio",
                            Opis = "Šumovito i planinsko područje s vrhovima poput Risnjaka, Snježnika i Skradskog vrha.",
                            Regija = "Gorska Hrvatska"
                        },
                        new
                        {
                            IdPodrucje = 10,
                            MinimalanBrojKTZaObilazak = 2,
                            Naziv = "Istra",
                            Opis = "Područje Učke i Ćićarije s istaknutim obalnim i planinskim vidikovcima.",
                            Regija = "Zapadna Hrvatska"
                        },
                        new
                        {
                            IdPodrucje = 11,
                            MinimalanBrojKTZaObilazak = 3,
                            Naziv = "Sjeverni Velebit",
                            Opis = "Visokoplaninsko područje s izrazito atraktivnim velebitskim vrhovima i oštrim kršem.",
                            Regija = "Primorsko-gorska Hrvatska"
                        },
                        new
                        {
                            IdPodrucje = 12,
                            MinimalanBrojKTZaObilazak = 2,
                            Naziv = "Srednji Velebit",
                            Opis = "Središnji dio Velebita sa srednje zahtjevnim i zahtjevnim vrhovima i planinarskim kućama.",
                            Regija = "Lika i Primorje"
                        },
                        new
                        {
                            IdPodrucje = 13,
                            MinimalanBrojKTZaObilazak = 3,
                            Naziv = "Južni Velebit",
                            Opis = "Najviši i alpinistički najdojmljiviji dio Velebita s Vaganskim vrhom i Svetim brdom.",
                            Regija = "Lika i Dalmacija"
                        },
                        new
                        {
                            IdPodrucje = 14,
                            MinimalanBrojKTZaObilazak = 1,
                            Naziv = "Lika",
                            Opis = "Prostrano područje ličkih planina i osamljenih vrhova izvan glavnog velebitskog lanca.",
                            Regija = "Lika"
                        },
                        new
                        {
                            IdPodrucje = 15,
                            MinimalanBrojKTZaObilazak = 1,
                            Naziv = "Jadranski otoci - sjeverni dio",
                            Opis = "Sjeverni jadranski otoci s nižim, ali vrlo atraktivnim otočnim vrhovima.",
                            Regija = "Jadranska Hrvatska"
                        },
                        new
                        {
                            IdPodrucje = 16,
                            MinimalanBrojKTZaObilazak = 2,
                            Naziv = "Jadranski otoci - južni dio",
                            Opis = "Južni jadranski otoci s većim brojem otočnih vrhova i raznolikim podlogama.",
                            Regija = "Jadranska Hrvatska"
                        },
                        new
                        {
                            IdPodrucje = 17,
                            MinimalanBrojKTZaObilazak = 2,
                            Naziv = "Dalmatinska zagora",
                            Opis = "Područje Dinare, Promine, Svilaje i drugih planina dalmatinskog zaleđa.",
                            Regija = "Dalmatinsko zaleđe"
                        },
                        new
                        {
                            IdPodrucje = 18,
                            MinimalanBrojKTZaObilazak = 2,
                            Naziv = "Dalmacija",
                            Opis = "Priobalno i zaleđno područje srednje Dalmacije s planinama uz obalu i u zaleđu.",
                            Regija = "Dalmacija"
                        },
                        new
                        {
                            IdPodrucje = 19,
                            MinimalanBrojKTZaObilazak = 3,
                            Naziv = "Biokovo i Zagora",
                            Opis = "Krševito visokoplaninsko područje Biokova i zaleđa s vrlo izraženim visinskim razlikama.",
                            Regija = "Južna Dalmacija"
                        },
                        new
                        {
                            IdPodrucje = 20,
                            MinimalanBrojKTZaObilazak = 1,
                            Naziv = "Dubrovačko područje",
                            Opis = "Južnohrvatsko područje s manjim brojem, ali vrlo atraktivnih kontrolnih točaka.",
                            Regija = "Krajnji jug Hrvatske"
                        });
                });

            modelBuilder.Entity("planinarenje.Entiteti.Posjet", b =>
                {
                    b.Property<int>("IdPosjet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPosjet"));

                    b.Property<DateTime>("DatumKreiranjaZapisa")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DatumVrijemePosjeta")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DozivljajPosjeta")
                        .HasColumnType("int");

                    b.Property<int>("IdKnjizica")
                        .HasColumnType("int");

                    b.Property<int>("IdKontrolnaTocka")
                        .HasColumnType("int");

                    b.Property<int>("IdKorisnik")
                        .HasColumnType("int");

                    b.Property<int>("IdRuta")
                        .HasColumnType("int");

                    b.Property<bool>("JeLiPotvrdenPosjet")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OpisIskustva")
                        .HasColumnType("longtext");

                    b.Property<string>("UneseniGUID")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("VrijemeUsponaMin")
                        .HasColumnType("int");

                    b.HasKey("IdPosjet");

                    b.HasIndex("IdKnjizica");

                    b.HasIndex("IdKontrolnaTocka");

                    b.HasIndex("IdKorisnik");

                    b.HasIndex("IdRuta");

                    b.ToTable("Posjeti");

                    b.HasData(
                        new
                        {
                            IdPosjet = 1,
                            DatumKreiranjaZapisa = new DateTime(2026, 4, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumVrijemePosjeta = new DateTime(2026, 4, 5, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            DozivljajPosjeta = 0,
                            IdKnjizica = 1,
                            IdKontrolnaTocka = 1,
                            IdKorisnik = 1,
                            IdRuta = 1,
                            JeLiPotvrdenPosjet = true,
                            OpisIskustva = "Prvi evidentirani uspon u aplikaciji. Lagana i ugodna ruta po suhom vremenu.",
                            UneseniGUID = "KT-HPO-2-1-VIS",
                            VrijemeUsponaMin = 92
                        },
                        new
                        {
                            IdPosjet = 2,
                            DatumKreiranjaZapisa = new DateTime(2026, 4, 12, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumVrijemePosjeta = new DateTime(2026, 4, 12, 8, 40, 0, 0, DateTimeKind.Unspecified),
                            DozivljajPosjeta = 5,
                            IdKnjizica = 1,
                            IdKontrolnaTocka = 3,
                            IdKorisnik = 1,
                            IdRuta = 3,
                            JeLiPotvrdenPosjet = true,
                            OpisIskustva = "Kratak, ali strm završni dio prema gradini Okić.",
                            UneseniGUID = "KT-HPO-5-1-OKIC",
                            VrijemeUsponaMin = 43
                        },
                        new
                        {
                            IdPosjet = 3,
                            DatumKreiranjaZapisa = new DateTime(2026, 4, 19, 11, 10, 0, 0, DateTimeKind.Unspecified),
                            DatumVrijemePosjeta = new DateTime(2026, 4, 19, 9, 10, 0, 0, DateTimeKind.Unspecified),
                            DozivljajPosjeta = 2,
                            IdKnjizica = 1,
                            IdKontrolnaTocka = 4,
                            IdKorisnik = 1,
                            IdRuta = 4,
                            JeLiPotvrdenPosjet = true,
                            OpisIskustva = "Ugodna tura s dobrim vremenom i lijepim pogledima s piramide.",
                            UneseniGUID = "KT-HPO-5-4-JAPETIC",
                            VrijemeUsponaMin = 96
                        },
                        new
                        {
                            IdPosjet = 4,
                            DatumKreiranjaZapisa = new DateTime(2026, 4, 8, 12, 45, 0, 0, DateTimeKind.Unspecified),
                            DatumVrijemePosjeta = new DateTime(2026, 4, 8, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            DozivljajPosjeta = 1,
                            IdKnjizica = 2,
                            IdKontrolnaTocka = 1,
                            IdKorisnik = 2,
                            IdRuta = 1,
                            JeLiPotvrdenPosjet = true,
                            OpisIskustva = "Testni korisnik uspješno evidentirao svoj prvi posjet i time zadovoljio uvjet za početničku medalju.",
                            UneseniGUID = "KT-HPO-2-1-VIS",
                            VrijemeUsponaMin = 95
                        },
                        new
                        {
                            IdPosjet = 5,
                            DatumKreiranjaZapisa = new DateTime(2026, 4, 26, 10, 40, 0, 0, DateTimeKind.Unspecified),
                            DatumVrijemePosjeta = new DateTime(2026, 4, 26, 7, 50, 0, 0, DateTimeKind.Unspecified),
                            DozivljajPosjeta = 7,
                            IdKnjizica = 2,
                            IdKontrolnaTocka = 2,
                            IdKorisnik = 2,
                            IdRuta = 2,
                            JeLiPotvrdenPosjet = true,
                            OpisIskustva = "Duži uspon do Sljemena preko Puntijarke, ali bez tehnički teških dijelova.",
                            UneseniGUID = "KT-HPO-4-4-SLJEME",
                            VrijemeUsponaMin = 155
                        });
                });

            modelBuilder.Entity("planinarenje.Entiteti.Ruta", b =>
                {
                    b.Property<int>("IdRuta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRuta"));

                    b.Property<decimal>("DuljinaKm")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("GPXPath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("GodinaObnove")
                        .HasColumnType("int");

                    b.Property<int>("IdKontrolnaTocka")
                        .HasColumnType("int");

                    b.Property<string>("Kraj")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Napomena")
                        .HasColumnType("longtext");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Opis")
                        .HasColumnType("longtext");

                    b.Property<string>("OznakaNaTerenu")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Pocetak")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("TezinaRute")
                        .HasColumnType("int");

                    b.Property<int?>("VisinskaRazlikaM")
                        .HasColumnType("int");

                    b.Property<int>("VrijemeHodaMin")
                        .HasColumnType("int");

                    b.HasKey("IdRuta");

                    b.HasIndex("IdKontrolnaTocka");

                    b.ToTable("Rute");

                    b.HasData(
                        new
                        {
                            IdRuta = 1,
                            DuljinaKm = 4.5m,
                            GPXPath = "C:\\GPX\\ruta_vis.gpx",
                            GodinaObnove = 2023,
                            IdKontrolnaTocka = 1,
                            Kraj = "Vrh Vis",
                            Napomena = "Pogodna za početnike.",
                            Naziv = "Kutina – Humka – Vis",
                            Opis = "Primjer kraće rute do najviše točke Moslavačke gore.",
                            OznakaNaTerenu = "MG-01",
                            Pocetak = "Kutina / Humka",
                            TezinaRute = 0,
                            VisinskaRazlikaM = 260,
                            VrijemeHodaMin = 90
                        },
                        new
                        {
                            IdRuta = 2,
                            DuljinaKm = 8.2m,
                            GPXPath = "C:\\GPX\\ruta_sljeme.gpx",
                            GodinaObnove = 2022,
                            IdKontrolnaTocka = 2,
                            Kraj = "Sljeme",
                            Napomena = "Jedna od najčešće korištenih ruta na Medvednici.",
                            Naziv = "Gračani – Puntijarka – Sljeme",
                            Opis = "Popularan uspon preko Puntijarke prema vrhu Medvednice.",
                            OznakaNaTerenu = "M-04",
                            Pocetak = "Gračani",
                            TezinaRute = 1,
                            VisinskaRazlikaM = 780,
                            VrijemeHodaMin = 150
                        },
                        new
                        {
                            IdRuta = 3,
                            DuljinaKm = 1.8m,
                            GPXPath = "C:\\GPX\\ruta_okic.gpx",
                            GodinaObnove = 2021,
                            IdKontrolnaTocka = 3,
                            Kraj = "Okić – vrh",
                            Napomena = "Strmiji završni dio prema gradini.",
                            Naziv = "Klake – pl. dom pod Okićem – Okić-grad",
                            Opis = "Najkraći klasični prilaz vrhu Okić preko doma pod Okićem.",
                            OznakaNaTerenu = "SG-01",
                            Pocetak = "Klake",
                            TezinaRute = 1,
                            VisinskaRazlikaM = 210,
                            VrijemeHodaMin = 40
                        },
                        new
                        {
                            IdRuta = 4,
                            DuljinaKm = 5.4m,
                            GPXPath = "C:\\GPX\\ruta_japetic.gpx",
                            GodinaObnove = 2020,
                            IdKontrolnaTocka = 4,
                            Kraj = "Japetić – vrh",
                            Napomena = "Ruta je pregledna i često korištena.",
                            Naziv = "Šoićeva kuća – Japetić",
                            Opis = "Klasičan prilaz preko livada i Katina krča prema vrhu Japetić.",
                            OznakaNaTerenu = "SG-04",
                            Pocetak = "Šoićeva kuća",
                            TezinaRute = 1,
                            VisinskaRazlikaM = 430,
                            VrijemeHodaMin = 90
                        },
                        new
                        {
                            IdRuta = 5,
                            DuljinaKm = 6.7m,
                            GPXPath = "C:\\GPX\\ruta_zavizan.gpx",
                            GodinaObnove = 2024,
                            IdKontrolnaTocka = 5,
                            Kraj = "Veliki Zavižan",
                            Napomena = "U nepovoljnim uvjetima potreban dodatni oprez.",
                            Naziv = "Dom Zavižan – Veliki Zavižan – dom Zavižan",
                            Opis = "Kružna tura s polaskom od doma Zavižan preko Balinovca do Velikog Zavižana.",
                            OznakaNaTerenu = "SV-02",
                            Pocetak = "Planinarski dom Zavižan",
                            TezinaRute = 2,
                            VisinskaRazlikaM = 320,
                            VrijemeHodaMin = 150
                        });
                });

            modelBuilder.Entity("planinarenje.Entiteti.Fotografija", b =>
                {
                    b.HasOne("planinarenje.Entiteti.Posjet", "Posjet")
                        .WithMany("Fotografije")
                        .HasForeignKey("IdPosjet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Posjet");
                });

            modelBuilder.Entity("planinarenje.Entiteti.Knjizica", b =>
                {
                    b.HasOne("planinarenje.Entiteti.Korisnik", "Korisnik")
                        .WithOne("Knjizica")
                        .HasForeignKey("planinarenje.Entiteti.Knjizica", "IdKorisnik")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("planinarenje.Entiteti.KontrolnaTocka", b =>
                {
                    b.HasOne("planinarenje.Entiteti.Podrucje", "Podrucje")
                        .WithMany("KontrolneTocke")
                        .HasForeignKey("IdPodrucje")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Podrucje");
                });

            modelBuilder.Entity("planinarenje.Entiteti.KorisnikMedalja", b =>
                {
                    b.HasOne("planinarenje.Entiteti.Korisnik", "Korisnik")
                        .WithMany("KorisnikMedalje")
                        .HasForeignKey("IdKorisnik")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("planinarenje.Entiteti.Medalja", "Medalja")
                        .WithMany("KorisnikMedalje")
                        .HasForeignKey("IdMedalja")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Medalja");
                });

            modelBuilder.Entity("planinarenje.Entiteti.Obavijest", b =>
                {
                    b.HasOne("planinarenje.Entiteti.Korisnik", "Korisnik")
                        .WithMany("Obavijesti")
                        .HasForeignKey("IdKorisnik")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("planinarenje.Entiteti.PlaninarskiObjekt", b =>
                {
                    b.HasOne("planinarenje.Entiteti.PlaninarskaUdruga", "PlaninarskaUdruga")
                        .WithMany("PlaninarskiObjekti")
                        .HasForeignKey("IdPlaninarskaUdruga")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("planinarenje.Entiteti.Podrucje", "Podrucje")
                        .WithMany("PlaninarskiObjekti")
                        .HasForeignKey("IdPodrucje")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlaninarskaUdruga");

                    b.Navigation("Podrucje");
                });

            modelBuilder.Entity("planinarenje.Entiteti.Posjet", b =>
                {
                    b.HasOne("planinarenje.Entiteti.Knjizica", "Knjizica")
                        .WithMany("Posjeti")
                        .HasForeignKey("IdKnjizica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("planinarenje.Entiteti.KontrolnaTocka", "KontrolnaTocka")
                        .WithMany("Posjeti")
                        .HasForeignKey("IdKontrolnaTocka")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("planinarenje.Entiteti.Korisnik", "Korisnik")
                        .WithMany("Posjeti")
                        .HasForeignKey("IdKorisnik")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("planinarenje.Entiteti.Ruta", "Ruta")
                        .WithMany("Posjeti")
                        .HasForeignKey("IdRuta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Knjizica");

                    b.Navigation("KontrolnaTocka");

                    b.Navigation("Korisnik");

                    b.Navigation("Ruta");
                });

            modelBuilder.Entity("planinarenje.Entiteti.Ruta", b =>
                {
                    b.HasOne("planinarenje.Entiteti.KontrolnaTocka", "KontrolnaTocka")
                        .WithMany("Rute")
                        .HasForeignKey("IdKontrolnaTocka")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KontrolnaTocka");
                });

            modelBuilder.Entity("planinarenje.Entiteti.Knjizica", b =>
                {
                    b.Navigation("Posjeti");
                });

            modelBuilder.Entity("planinarenje.Entiteti.KontrolnaTocka", b =>
                {
                    b.Navigation("Posjeti");

                    b.Navigation("Rute");
                });

            modelBuilder.Entity("planinarenje.Entiteti.Korisnik", b =>
                {
                    b.Navigation("Knjizica")
                        .IsRequired();

                    b.Navigation("KorisnikMedalje");

                    b.Navigation("Obavijesti");

                    b.Navigation("Posjeti");
                });

            modelBuilder.Entity("planinarenje.Entiteti.Medalja", b =>
                {
                    b.Navigation("KorisnikMedalje");
                });

            modelBuilder.Entity("planinarenje.Entiteti.PlaninarskaUdruga", b =>
                {
                    b.Navigation("PlaninarskiObjekti");
                });

            modelBuilder.Entity("planinarenje.Entiteti.Podrucje", b =>
                {
                    b.Navigation("KontrolneTocke");

                    b.Navigation("PlaninarskiObjekti");
                });

            modelBuilder.Entity("planinarenje.Entiteti.Posjet", b =>
                {
                    b.Navigation("Fotografije");
                });

            modelBuilder.Entity("planinarenje.Entiteti.Ruta", b =>
                {
                    b.Navigation("Posjeti");
                });
#pragma warning restore 612, 618
        }
    }
}
